# Generated by Django 5.0.2 on 2024-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
