# Generated by Django 5.0.2 on 2024-04-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_car_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarCondition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("condition", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CarStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_condition",
                to="cars.carcondition",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_status",
                to="cars.carstatus",
            ),
        ),
    ]
